@startmindmap
* GDK
** gdk
*** GameModule.java
*** GameMetadata.java
*** Logging.java
*** MessagingBridge.java
** launcher
*** gui
**** GDKGameLobbyController.java
**** GDKViewModel.java
**** ServerSimulatorController.java
**** SettingsPageController.java
**** SingleJsonEditor.java
*** utils
**** ModuleCompiler.java
**** ModuleDiscovery.java
**** GameLaunchUtil.java
**** StartMessageUtil.java
**** TranscriptRecorder.java
**** DialogUtil.java
*** lifecycle
**** start
***** Startup.java
***** StartupOperations.java
***** UIInitializer.java
***** startup_window
****** PreStartupProgressWindow.java
****** ProgressBarStyling.java
****** StartupWindowManager.java
**** stop
***** Shutdown.java
*** GDKApplication.java
** modules
*** Chatroom
**** Main.java
**** Metadata.java
@endmindmap
